[package]
name = "blochs-config"
version = "0.1.0"
authors = ["Jean Jung <jean.jung@rocketmail.com>"]
description = "Blochs database configuration tool"

[dependencies]
clap = "~2.24.0"
libblochs = { path = "../libblochs" }

